### ISSUE TITLE
Method to list socket ids in a room

### ISSUE THREAD

**Issue by download13** [Automattic/socket.io-adapter#14]
I was writing something and came across a problem. I need a way to get the id of every socket in a room.

According to [stackoverflow](http://stackoverflow.com/questions/6563885/socket-io-how-do-i-get-a-list-of-connected-sockets-clients) there used to be a way to do this. It should really be standard.

A `list(room)` method on the adapter would do nicely since that's the place where you normally work with rooms. I might submit a pull request before anyone comments on this, but it can always be updated later.

**Comment by rauchg** [comment]
Duplicate
